### ISSUE TITLE
Can't build with Nix on OSX due to upstream dependency issues

### ISSUE THREAD

**Issue by shanesveller** [serokell/nixfmt#10]
This is mostly meant as a connect-the-dots informational issue for other users, and likely not something that requires meaningful local project changes, only patience and perhaps a bump to `/nixpkgs.nix` when the time is right.

On OSX (10.14.4 in my specific case), the committed `nixpkgs.nix` as of 686753ce519954cbc45c4c48c73f1bd7744dc9c3 file generates errors from the `lz4` package with a snippet like so, when used simply via `nix-build -j 1 --no-out-link` at the root of this project: 

```
build flags: -j1 -l1 SHELL=/nix/store/5544q4fyc2cr0raqv6c6xhx6d9z1ccdj-bash-4.4-p23/bin/bash PREFIX=\$\(out\) INCLUDEDIR=\$\(dev\)/include
make[1]: Entering directory '/private/tmp/nix-build-lz4-1.9.1.drv-0/source/lib'
compiling static library
compiling dynamic library 1.9.1
ld: unknown option: -soname=liblz4.so.1
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:113: liblz4.so.1.9.1] Error 1
make[1]: Leaving directory '/private/tmp/nix-build-lz4-1.9.1.drv-0/source/lib'
make: *** [Makefile:52: lib-release] Error 2
builder for '/nix/store/y0600jph012wbcmnam82y8g7i0if78rl-lz4-1.9.1.drv' failed with exit code 2
```

Moving to a newer commit of nixpkgs, similar to this diff which uses the current tip of `master`, does successfully complete via `nix-build`, which agrees with the content of the related nixpkgs issue/PR linked down below.

```diff
diff --git a/nixpkgs.nix b/nixpkgs.nix
index 60d2db9..2f117c1 100644
--- a/nixpkgs.nix
+++ b/nixpkgs.nix
@@ -1,4 +1,4 @@
 import (fetchTarball {
-  url = "https://github.com/NixOS/nixpkgs/archive/bc94dcf500286495e3c478a9f9322debc94c4304.tar.gz";
-  sha256 = "1siqklf863181fqk19d0x5cd0xzxf1w0zh08lv0l0dmjc8xic64a";
+  url = "https://github.com/NixOS/nixpkgs/archive/f259157647b46fdc087bd9d41d4f983968c5b92f.tar.gz";
+  sha256 = "1agih8q8pchadyv3wbmwrw2yxw8rii1iwyy5wckslq4njrdzijma";
 }) { config = {}; overlays = []; }
```

AFAIK the required changes have not yet landed in the `nixpkgs-19.03-darwin` channel and would affect many other applications besides this one, if `lz4` winds up in their dependency tree somewhere.

Refs:
https://github.com/NixOS/nixpkgs/issues/61319
https://github.com/NixOS/nixpkgs/pull/60849

**Comment by Lucus16** [comment]
Thank you for bringing this to our attention! Please let us know when the solution arrives in the darwin channel and we should repin.

**Comment by yorickvP** [comment]
Fixed
