### ISSUE TITLE
No binary for v0.6.0 release?

### ISSUE THREAD

**Issue by edslocomb** [serokell/nixfmt#139]
Hi, I've been working on an emacs package, Apheleia, that supports nixfmt.

For testing, it's awfully convenient to just download a binary without having to install Nix on the CI server.  v0.5.0 had a binary, v0.6.0 does not-- is there any chance that could be added?

**Comment by infinisil** [comment]
I'm not sure how the previous static binary was created, there's no Nix setup for that. @yorickvP you did the previous release, how did you generate that? https://github.com/serokell/nixfmt/releases/tag/v0.5.0

**Comment by Lucus16** [comment]
I'm guessing build the flake outputs locally and push them to cachix manually.

**Comment by infinisil** [comment]
@Lucus16 The release artifacts include a static binary, but no Flake output produce that (not even nixfmt-static)

**Comment by yorickvP** [comment]
I don't remember, but presumably I built pkgsStatic.nixfmt-static

**Comment by infinisil** [comment]
Nice that worked, I tried that out before but was worried it was gonna rebuild too much, turns out it's not too much.

@edslocomb Release now contains a static binary: https://github.com/serokell/nixfmt/releases/tag/v0.6.0 :)

**Comment by edslocomb** [comment]
awesome, thanks!
