### ISSUE TITLE
Replaces tabulator characters inside quotes

### ISSUE THREAD

**Issue by mcnesium** [serokell/nixfmt#146]
The formatter replaces tabulator characters inside quotes. This breaks e.g. shell alias config:

```
[mcn@x2b:/etc/nixos]$ nixfmt --version
nixfmt v0.6.0

[mcn@x2b:/etc/nixos]$ nixfmt home.nix 

[mcn@x2b:/etc/nixos]$ git diff home.nix 
    shellAliases = {
       dops =
-        "docker ps --format 'table {{.Image}}\t{{.Names}}\t{{.Status}}\t{{.RunningFor}}\t{{.Size}}\t{{.Ports}}'";
+        "docker ps --format 'table {{.Image}}  {{.Names}}      {{.Status}}     {{.RunningFor}} {{.Size}}       {{.Ports}}'";
```

**Comment by piegamesde** [comment]
Hi, can you please try this out on #118?

**Comment by mcnesium** [comment]
ok I tried doing `nix shell github:piegamesde/nixfmt/rfc101-style`. This installed v0.5.0 in the shell. Is that correct? I am on NixOS 23.11 and on my system there is v0.6.0 installed.

So yes, v0.5.0 also replaces quoted tabulators

**Comment by piegamesde** [comment]
The version names are meaningless on development branches. It just means that the branch was forked off before the recent 0.6.0 release.

Can you please also provide a complete (preferably minimal) input which reproduces your issue? I tried with just the string and some other combinations, but could not reproduce it somehow.

**Comment by mcnesium** [comment]
A really minimal example is only a `test.nix` with `{ test = "'foo\tbar'"; }` that will expand the `\t` to an actual tab character. However, I don't know whether that is a good example because it probably violates a proper .nix file structure. So here is one that should work:

    { config, pkgs, ... }:

    {
      programs.bash = {
        shellAliases = {
          test = "echo 'foo\tbar'";
        };
      };
    }

**Comment by piegamesde** [comment]
Ooh. Your issue is that it replaces `\t` with `	`? Yes, that may happen, and is allowed as it changes nothing in the evaluation. The diff you initially showed had the `\t` replaced with a bunch of spaces, which indeed would have been an error. (Also, your minimal example is totally valid Nix code)

Could it be that you are confusing `\t` and `\\t`?

**Comment by mcnesium** [comment]
Ah yes! I missed that when I copied the lines from the old bash config. Sorry for the noise.

Turns out, the bash alias even works both ways: having a `\\t` in the .nix-file or having it transformed to an actual tab character by this obviously correctly working formatter :+1:

**Comment by ursi** [comment]
This is unacceptable behavior. Unless you're using them for formatting a large multiline string that is going go be printed, I don't see why you would ever want to use a literal tab inside a string. It just looks like a bunch of spaces and therefore does not communicate the proper source code to the reader. Please remove this conversion.
