### ISSUE TITLE
Formatting Result Should be the Unaltered Input on Error

### ISSUE THREAD

**Issue by Lord-Valen** [serokell/nixfmt#148]
Whenever there is a syntax error, the formatter should take the more robust approach of returning the original contents rather than nothing. This isn't an issue for cli usage, as `nixfmt` won't write to a file when there is a syntax error. This approach makes more sense for use with scripts and language-servers, which may take the `stdout` (or lack thereof) as the formatting result, thereby erasing file contents.

**Comment by piegamesde** [comment]
*taps the sign* https://flausch.social/@piegames/108079708503510828

**Comment by Lord-Valen** [comment]
> Any decent script or language server should check the exit code in order to determine whether formatting was successful and replace the contents with the output of `stdout` if it was and report the error in `stderr` through some other channel to the user if it wasn't. 

I agree that scripts and language servers *should* do that but they do not always keep to these standards. The need for them to do this is to make the fewest possible assumptions as to how the formatter operates for the sake of the user. Similarly, the formatter should not assume that scripts and language servers will respect the exit code and also work to the benefit of the user. With this method the user is most likely to be protected from misapplied formatting.

> This is how most formatters work.

This is not how most **nix** formatters work. `nixpkgs-fmt` and `alejandra` use a non-zero exit code *and* output the original contents to `stdout` on syntax error. Besides, I think evaluating a feature based on how frequently it is implemented is rather poor compared to evaluating it on its merit.

**Comment by Lord-Valen** [comment]
> *taps the sign* https://flausch.social/@piegames/108079708503510828

That's true, but so is deaf error handling. We should prepare for both imo. Providing the original contents to `stdout` doesn't stop us from piping error information to `stderr` or exiting with a non-zero code. No silence here nor should there be.

**Comment by Lucus16** [comment]
I don't think a formatter should ever generate unformatted output. That is the opposite of what one expects it to do. Checking the exit code is not hard. If a script does not check the exit code, the bug is in the script, not in nixfmt.

**Comment by piegamesde** [comment]
Moreover, printing files to stdout is not compatible with formatting multiple files at once, which may fail individually.

FWIW, it should be easy to wrap `nixfmt` in a bit of shell to emulate the functionality you want: `nixfmt "$@" || cat "${@: -1}"` (this assumes you only passed a single file to the invocation)
