### ISSUE TITLE
[RFC 101] nixfmt is not idempotent

### ISSUE THREAD

**Issue by eclairevoyant** [serokell/nixfmt#150]
Tested against ca1fe3572ea6134551ee6af40ae735a1a1ed0d35

input:
```nix
{
  a = {

  };
}
```

output (round 1):
```nix
{
  a = {
    };
}
```

output (round 2):
```nix
{ a = { }; }
```

**Comment by piegamesde** [comment]
Thanks, this is a known issue. Until yesterday it was blocked on the RFC discussion, because I was not sure whether the fix should preserve the empty line here or not. I'll start working on this in the next days.

**Comment by piegamesde** [comment]
Should be fixed now, please test against 22fa00e788c891171946fc0ccfd349f946ce579e

**Comment by eclairevoyant** [comment]
works now, thanks!
