### ISSUE TITLE
Default arguments and line breaks

### ISSUE THREAD

**Issue by acowley** [serokell/nixfmt#31]
### Description
Avoid adding line breaks before function parameters and corresponding default values.

### Small example input

I saw an announcement regarding this tool, and the first example I took a look at was [emacs](https://github.com/serokell/nixpkgs/blob/formatted/pkgs/applications/editors/emacs/default.nix). I was not expecting the increasing indentation of function parameters, and the line breaks after the `?` characters makes reading the default values more challenging.

### Expected output

Treat function parameters specially by not inserting line breaks between parameter names and default values. 

Wrap parameter lists at commas.

Do not increase the indentation level within a parameter list.

**Comment by Lucus16** [comment]
Thank you for reporting this, #33 should fix this for now, though I intend to improve set abstractions further in the future.

**Comment by kirelagin** [comment]
Fore reference, the original report pointed at https://github.com/serokell/nixpkgs/blob/f4c1a663a6fd9f6de8f248ff9ae80fd0595dc678/pkgs/applications/editors/emacs/default.nix
