### ISSUE TITLE
Include nixfmt in nixpkgs

### ISSUE THREAD

**Issue by offlinehacker** [serokell/nixfmt#36]
There's currently no usable nix formatter tool in nixpkgs. I think it would be nice to include nixfmt in nixpkgs, so there's a tool we can install for formatting of nix code, off the shelf.

**Comment by matthew-piziak** [comment]
Agreed. I currently install it like this:
```
{ config, pkgs, ... }:
let
  nixfmt = import (pkgs.fetchFromGitHub {
    owner = "serokell";
    repo = "nixfmt";
    rev = "af09262aa7d08d2b0905b11d2e8958889aadcf46"; # v0.2.0
    sha256 = "0njgjv6syv3sk97v8kq0cb4mhgrb7nag2shsj7rphs6h5b7k9nbx";
  }) { };
in {
  environment.systemPackages = ([ nixfmt ]);
}
```

**Comment by Lucus16** [comment]
That makes sense. I'll upload it to hackage after which it should eventually appear under `haskellPackages.nixfmt`.

**Comment by kirelagin** [comment]
@offlinehacker It would be great if you could help with NixOS/nixpkgs#68013 :).

**Comment by jagajaga** [comment]
https://github.com/NixOS/nixpkgs/pull/68013
