### ISSUE TITLE
Escapes in ''-quoted strings are lost during formatting.

### ISSUE THREAD

**Issue by Sean1708** [serokell/nixfmt#42]
The expression

```nix
let
  shAppend = name: value: ''
    export ${name}="${value}:''$${name}"
  '';
in { foo = shAppend "PATH" "$HOME/.local/bin"; }
```

gets formatted as

```nix
let
  shAppend = name: value: ''
    export ${name}="${value}:$${name}"
  '';
in { foo = shAppend "PATH" "$HOME/.local/bin"; }
```

which drops the `''` from the `''$` escape sequence. With the escape sequence the result is

```sh
export PATH="$HOME/.local/bin:$PATH"
```

but without it you get:

```sh
export PATH="$HOME/.local/bin:$${name}"
```

**Comment by Lucus16** [comment]
Thanks for reporting! Looks like `$$` and `''` combine a lot more messily than I originally thought. I'll try to figure out the rules behind it.

**Comment by Sean1708** [comment]
Thank you @Lucus16 and @yorickvP!!
