### ISSUE TITLE
Does not accept floats without 0

### ISSUE THREAD

**Issue by yorickvP** [serokell/nixfmt#48]
```
nix-repl> x: {}.5
«lambda @ (string):1:1»
```

```
nix-repl> [1.2.3.4.5]
[ 1.2 0.3 0.4 0.5]
```

nixfmt does not parse these. Maybe it shouldn't.

**Comment by balsoft** [comment]
How do you even come up with something like this?

I'd say WONTFIX and file a bug upstream :smile:

**Comment by yorickvP** [comment]
It was in #nixos-chat. The hope is to remove floats from nix, they are only used in json parsing and the tests for printing floats :D.

**Comment by Lucus16** [comment]
I agree with @balsoft. I'm willing to be more strict than official Nix here.
