### ISSUE TITLE
Backslash stripping produces invalid code

### ISSUE THREAD

**Issue by manveru** [serokell/nixfmt#69]
### Description

Another case of string interpolation goes wrong and produces incorrect code. For some reason the backslash in `"$\${"` is stripped away, producing invalid code.

### Small example input

```nix
replaceStrings ["\${"] ["$\${"] "\${hello}"
```

### Expected output

```nix
replaceStrings [ "\${" ] [ "$\${" ] "\${hello}"
```

### Actual output

```nix
replaceStrings [ "\${" ] [ "$${" ] "\${hello}"
```

**Comment by Lucus16** [comment]
Actually, you might want to try that in `nix repl`. :)

For some reason, in Nix, two consecutive dollar signs escape each other and prevent a string interpolation from forming. In this case, `nixfmt` correctly removes the bogus backslash.
