### ISSUE TITLE
Please, allow not only "Formatting suggestion" reports but also general reports

### ISSUE THREAD

**Issue by Anton-Latukha** [serokell/nixfmt#70]
Hi!

Currently, the report template is monodirectional, only "Formatting suggestions".

Well, I think that means you stating that the code is ideal then, well it may be :smile:

**Comment by yorickvP** [comment]
There's a  "Don’t see your issue here? Open a blank issue. " link on the "New Issue" page that should suffice for everything that's not a formatting suggestion, I hope.
