### ISSUE TITLE
nixfmt breaks trailing spaces in strings when doing "" to '''' conversion

### ISSUE THREAD

**Issue by jkarlson** [serokell/nixfmt#78]
nixfmt seems to make a1 like a2 and b1 like b2, while they are different strings in 
[testin.txt](https://github.com/serokell/nixfmt/files/7176993/testin.txt)

**Comment by jkarlson** [comment]
eg. try before and after
```
nix eval '( let test = import ./test.nix; in test.a1 == test.a2)'
```

**Comment by Lucus16** [comment]
Very interesting. It seems Nix strips trailing spaces on the final pseudo-line if and only if it consists of only spaces. I did not know about this behavior. This can be fixed best by adding a step to the `fixIndentedString` function in `src/Nixfmt/Parser.hs` which maps the raw lines read in a file to the lines the string is supposed to represent. I'll try to make time for that soon, or feel free to give it a try. Thanks for the report!
