### ISSUE TITLE
`numtide/treefmt` compatibility

### ISSUE THREAD

**Issue by yorickvP** [serokell/nixfmt#88]
User report:

> I set up treefmt for my editor and nixfmt fails formatting without any obvious sign.
> Maybe the spec is incomplete, but I think it had to do with some sort of temp-file mutation. iirc.
> Maybe treefmt and nixfmt are competing on the file-handling domain in incompatible ways?

**Comment by yorickvP** [comment]
@blagacao

**Comment by yorickvP** [comment]
@blaggacao

**Comment by SebTM** [comment]
I would like to hijack this as nixfmt was added by me to treefmt without seeing this - it works fine (from formatting output) but it changes mtime even file didn't had to be reformatted which was reported [here](https://github.com/numtide/treefmt-nix/issues/99) and violates the [idempotence](https://numtide.github.io/treefmt/formatters-spec/#3-idempotent) requirement from treefmt.

Sadly I don't have any Haskell knowledge and currently no time to get into so I would appreciate if someone could help out here :v:
