### ISSUE TITLE
Support single '-' operand and take it as reading from standard input

### ISSUE THREAD

**Issue by terlar** [serokell/nixfmt#99]
Currently passing the argument `-` does not try to read the "file" from standard input.

E.g.:
```
nixfmt - < flake.nix
```

This is a common standard as suggested per [POSIX](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap12.html#tag_12_02).

This is especially required if using nixfmt via flake formatter `nix fmt`. As `nix fmt` does not handle standard input by default, but you need to run `nix fmt -- -`. One could also argue that it would be neat if `nix fmt` supported this.

**Comment by terlar** [comment]
Speaking of compatibility with `nix fmt`. Just plainly running `nix fmt` doesn't work as that will invoke. `nixfmt .` which is also not supported by `nixfmt`.

```
$ nix fmt
nixfmt: .: openFile: inappropriate type (is a directory)
```

**Comment by Lucus16** [comment]
nixfmt already reads from stdin by default when no positional argument is passed.

**Comment by terlar** [comment]
Yeah, I guess `nix fmt` could be changed as well. Currently it does not support forwarding stdin by default, but you need to provide a `-` in order to get that behavior. This could probably be changed.

Should I rename the issue to be about `nix fmt` compatibility. Perhaps this is something that should be raised on that end as well, seeing it is still part of the unstable API.
